MultiShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("account.urls")),
    path('products/', include("product.urls")),
    path('cart/', include("cart.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import CartDetailView, CartAddView, CartDeleteView, OrderDetailView, OrderCreationView, ApplyDiscountView, \
    SendRequestView, VerifyView


app_name = 'cart'
urlpatterns = [
    path('detail', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', CartAddView.as_view(), name='cart_add'),
    path('delete/<str:id>', CartDeleteView.as_view(), name='cart_delete'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('order/add', OrderCreationView.as_view(), name='order_creation'),
    path('applydiscount/<int:pk>', ApplyDiscountView.as_view(), name='apply_discount'),
    path('sendrequest/<int:pk>', SendRequestView.as_view(), name='send_request'),
    path('verify/', VerifyView.as_view(), name='verify_request'),
]

product/urls.py
from django.urls import path
from .views import ProductDetailView, NavbarPartialView, CategoryStyle, ProductsListView, search


app_name = 'product'
urlpatterns = [
    path('all', ProductsListView.as_view(), name='products_list'),
    path('<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('navbar', NavbarPartialView.as_view(), name='navbar'),
    path('category', CategoryStyle.as_view(), name='category'),
    path('search/', search, name='search'),
]

product/models.py
from django.db import models


class Category(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='subs')
    title = models.CharField(max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Size(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=30)
    description = models.TextField()
    price = models.IntegerField()
    discount = models.SmallIntegerField()
    cover = models.ImageField(upload_to='products')
    size = models.ManyToManyField(Size, blank=True, related_name='products')
    color = models.ManyToManyField(Color, blank=True, related_name='products')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title


class Information(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE, related_name='informations')
    text = models.TextField()

    def __str__(self):
        return self.text[:60]


class Image(models.Model):
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE, related_name='images')
    file = models.ImageField(upload_to='products')

    def __str__(self):
        return self.file.url

product/views.py
from django.shortcuts import render
from django.views.generic import DetailView, TemplateView, ListView
from .models import Product, Category
from django.core.paginator import Paginator


class ProductDetailView(DetailView):
    template_name = "product/product_detail.html"
    model = Product


class NavbarPartialView(TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super(NavbarPartialView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class CategoryStyle(TemplateView):
    template_name = 'category.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryStyle, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class ProductsListView(ListView):
    template_name = 'product/products_list.html'
    queryset = Product.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')
        colors = request.GET.getlist('color')
        sizes = request.GET.getlist('size')
        queryset = Product.objects.all()
        filter_queryset = Product.objects.all()
        page_number = request.GET.get('page')
        paginator = Paginator(queryset, 1)
        queryset = paginator.get_page(page_number)

        if colors:
            queryset = filter_queryset.filter(color__title__in=colors).distinct()
            page_number = request.GET.get('page')
            paginator = Paginator(queryset, 1)
            queryset = paginator.get_page(page_number)
        if sizes:
            queryset = filter_queryset.filter(size__title__in=sizes).distinct()
            page_number = request.GET.get('page')
            paginator = Paginator(queryset, 1)
            queryset = paginator.get_page(page_number)
        if min_price and max_price:
            queryset = filter_queryset.filter(price__lte=max_price, price__gte=min_price)
            page_number = request.GET.get('page')
            paginator = Paginator(queryset, 1)
            queryset = paginator.get_page(page_number)

        context = super(ProductsListView, self).get_context_data()
        context['object_list'] = queryset
        return context


def search(request):
    q = request.GET.get('q')
    queryset = Product.objects.filter(title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(queryset, 1)
    queryset = paginator.get_page(page_number)
    return render(request, 'product/products_list.html', {'object_list': queryset})

product/templates/product/products_list.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shop List</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span>
                </h5>
                <form>
                    <div class="bg-light p-4 mb-30">
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <label for="price-all">Min</label>
                            <input type="number" name="min_price" id="price-all">
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <label for="price-all">Max</label>
                            <input type="number" name="max_price" id="price-all">
                        </div>


                    </div>
                    <!-- Price End -->

                    <!-- Color Start -->
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span>
                    </h5>
                    <div class="bg-light p-4 mb-30">

                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Black" class="custom-control-input" id="color-1">
                            <label class="custom-control-label" for="color-1">Black</label>
                            <span class="badge border font-weight-normal">150</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="White" class="custom-control-input" id="color-2">
                            <label class="custom-control-label" for="color-2">White</label>
                            <span class="badge border font-weight-normal">295</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Red" class="custom-control-input" id="color-3">
                            <label class="custom-control-label" for="color-3">Red</label>
                            <span class="badge border font-weight-normal">246</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Blue" class="custom-control-input" id="color-4">
                            <label class="custom-control-label" for="color-4">Blue</label>
                            <span class="badge border font-weight-normal">145</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                            <input type="checkbox" name="color" value="Green" class="custom-control-input" id="color-5">
                            <label class="custom-control-label" for="color-5">Green</label>
                            <span class="badge border font-weight-normal">168</span>
                        </div>

                    </div>
                    <!-- Color End -->

                    <!-- Size Start -->
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span>
                    </h5>
                    <div class="bg-light p-4 mb-30">

                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="size" value="XS" class="custom-control-input" id="size-1">
                            <label class="custom-control-label" for="size-1">XS</label>
                            <span class="badge border font-weight-normal">150</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="size" value="X" class="custom-control-input" id="size-2">
                            <label class="custom-control-label" for="size-2">X</label>
                            <span class="badge border font-weight-normal">295</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="size" value="L" class="custom-control-input" id="size-3">
                            <label class="custom-control-label" for="size-3">L</label>
                            <span class="badge border font-weight-normal">246</span>
                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="size" value="M" class="custom-control-input" id="size-4">
                            <label class="custom-control-label" for="size-4">M</label>
                            <span class="badge border font-weight-normal">145</span>
                        </div>
                    </div>
                    <input type="submit">
                </form>
                <!-- Size End -->
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Sorting
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">Latest</a>
                                        <a class="dropdown-item" href="#">Popularity</a>
                                        <a class="dropdown-item" href="#">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Showing
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">10</a>
                                        <a class="dropdown-item" href="#">20</a>
                                        <a class="dropdown-item" href="#">30</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                            <div class="product-item bg-light mb-4">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="{{ product.cover.url }}" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-sync-alt"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                <div class="text-center py-4">
                                    <a class="h6 text-decoration-none text-truncate" href="{% url 'product:product_detail' product.id %}">{{ product.title }}</a>
                                    <div class="d-flex align-items-center justify-content-center mt-2">
                                        <h5>${{ product.price }}</h5>
                                        <h6 class="text-muted ml-2">
                                            <del>$123.00</del>
                                        </h6>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% if object_list.has_other_pages %}
                        <div class="col-12">
                            <nav>
                                <ul class="pagination justify-content-center">
                                    {% if object_list.has_previous %}
                                        <li class="page-item"><a class="page-link"
                                                                          href="?page={{ object_list.previous_page_number }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}">Previous</a>
                                        </li>
                                    {% endif %}
                                    {% for i in object_list.paginator.page_range %}
                                        {% if object_list.number == i %}
                                            <li class="page-item active"><a class="page-link"
                                                                            href="?page={{ i }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}">{{ i }}</a></li>
                                        {% elif i > object_list.number|add:'-3' and i < object_list.number|add:'3' %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if object_list.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ object_list.next_page_number }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}">Next</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% endif %}

                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->
{% endblock %}